### ISSUE TITLE
individual channel to send levels and mutes

### ISSUE THREAD

**Issue by nottooloud** [bitfocus/companion-module-behringer-x32#9] opened 2020-03-08 18:35 UTC
Requesting individual "channel to send" levels and mutes.

**Comment by istnv** [comment] 2020-03-08 20:03
It's already there:
Add a button, add action 'Set mute' or 'Set fader level'.
There is a drop down to select the channel.

**Comment by nottooloud** [comment] 2020-03-08 20:20
That sets a channel mute or fader to the L/R.

Requesting another drop down to select the mix bus.

**Comment by istnv** [comment] 2020-03-08 20:32
There is another 'Set fader level' action that allows you to choose channel,AuxIn,FXrtn,Bus,Mtx or DCA. Those will set the master aux/bus levels.
Or are you asking for a channel to bus sends?
That is in the XAir module, but I don't see it in X32.

**Comment by nottooloud** [comment] 2020-03-08 21:06
> Or are you asking for a channel to bus sends?

Exactly. Also the associated individual mutes, which the X32 mixer has but XAir doesn't .

**Comment by Julusian** [comment] 2020-05-12 16:16
Duplicate of #11

**Closed by Julusian** 2020-05-12 16:16 UTC
