### ISSUE TITLE
Module does not connect to M32R

### ISSUE THREAD

**Issue by JimDeBarker** [bitfocus/companion-module-behringer-x32#31] opened 2020-09-19 17:09 UTC
Thanks for the great code. Having an issue connecting to the small format M32R. Desk is running latest 4.x firmware and connected properly to network. M32-Edit connects and can control the desk from another computer ok. Companion version is 2.1.1-2de-1549-2569.

In the GUI the connection is stuck on "syncing" with a yellow background. Having read other threads I have attempted to send commands from companion anyway but these commands are not received by the desk. Attached is screenshot showing state of the connect when I select EDIT on the instance. Model and firmware are undefined, could this be an issue with the code not recognising the smaller format models of the desk?
![Capture](https://user-images.githubusercontent.com/71563610/93673781-4dcb3e00-faa3-11ea-95c7-90fe28356f35.JPG)

**Comment by Julusian** [comment] 2020-09-25 20:17
There was a bug fixed in 2578 that would prevent the module connecting to a device after the config was updated. Perhaps you are hitting that issue?
If it connects after restarting companion then that will confirm that to be the cause.

As far as im aware the functionality of the various x32/m32 models is identical, just with a different form factor, so the module should work fine with them all.

Actually, the commands not working looks like a clue here, and suggests that the companion computer isnt able to talk to the m32.
In fact, the syncing state is a bit misleading, syncing really means that it is waiting for the first osc response from the desk.

**Comment by Julusian** [comment] 2022-01-03 22:19
assumed fixed

**Closed by Julusian** 2022-01-03 22:19 UTC
Labels: question
